# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeetTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeetTracker
  pod 'Alamofire', '~> 4.0'
  pod 'SQLite.swift', '~> 0.11.0'
  pod 'Kanna', '~> 2.0.0'
end
